### ISSUE TITLE
Inview Loading

### ISSUE THREAD

**Issue by suhmantha1** [UseAllFive/ani-friend#3]
On page start there is content in view that doesn't get loaded until you scroll, so it looks like there is a bunch of blank space. This is really apparent on some Golden Road pages with short hero sections and then like half the page is white space until you scroll a px to init the ani-animation

https://cl.ly/d8e9ec03c097

**Comment by suhmantha1** [comment]
cc @jasonfarrell ^^

**Comment by jasonfarrell** [comment]
@suhmantha1 it's because the group needs to be in view at whatever `inViewTriggerPercent` is set to. You could set it to zero, and up the `initialDelay`.

Maybe I should also let you override the inViewTriggerPercent on individual groups? So you could set that one to zero.

**Comment by suhmantha1** [comment]
I like the idea of being able to override `inViewTriggerPercent` for specific content that you know will be high up on page. Or also potentially having a single place where you can set that value for sites where client is adding content and placement on the page is variable

**Comment by jasonfarrell** [comment]
Not sure I follow the second part — but here's an `ani-in-view-trigger-percent` param for the top group. `1.0.24`

**Comment by suhmantha1** [comment]
@jasonfarrell wondering if there's a way to set that param as a default for an entire project instead of adding to each component? Not an issue for this project because we're controlling alot of the component placement, but would be an issue where page layouts are more variable and a component might be placed at the top of the page sometimes, and not at others. does that make sense?

**Comment by jasonfarrell** [comment]
Yep — `AniConfig.inViewTriggerPercent = 0.1`

In the golden road project, you can find it in `src/utils/animation.js` line 7
