### ISSUE TITLE
Image Alt Tag 

### ISSUE THREAD

**Issue by suhmantha1** [UseAllFive/ani-friend#7]
@jasonfarrell using `data-load-src` on image tags is clearing the alt tags

**Comment by jasonfarrell** [comment]
@suhmantha1 I think this is golden road specific. I tested on the library and the alt attributes remain, in all types of animations. Can you share?

**Comment by suhmantha1** [comment]
hmm yeah you're right. seems like gatsby isnt always returning the alt tag
